const colors = {
  light: {
    text: "#0D1B2A",
    tint: "#1A3A5C",
    background: "#F5F7FA",
    foreground: "#0D1B2A",
    card: "#FFFFFF",
    cardForeground: "#0D1B2A",
    primary: "#1A3A5C",
    primaryForeground: "#FFFFFF",
    secondary: "#E4EAF1",
    secondaryForeground: "#1A3A5C",
    muted: "#EBF0F6",
    mutedForeground: "#6B7E93",
    accent: "#2A6496",
    accentForeground: "#FFFFFF",
    destructive: "#C0392B",
    destructiveForeground: "#FFFFFF",
    border: "#D1DAE4",
    input: "#D1DAE4",
    success: "#1A7A4A",
    warning: "#B8860B",
    overlay: "rgba(13,27,42,0.55)",
    calcBackground: "#1C1C1E",
    calcDisplay: "#1C1C1E",
    calcDigit: "#3A3A3C",
    calcOperator: "#FF9500",
    calcSpecial: "#636366",
    calcText: "#FFFFFF",
    calcDisplayText: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
